version: "3.8"

services:
  backend:
    container_name: loja_backend
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
  frontend:
    container_name: loja_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
  db:
    container_name: loja_db
    image: mysql:8.3.0
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
volumes:
  mysql_data:
  mysql_config:
